### ISSUE TITLE
One needle point not showing up??

### ISSUE THREAD

**Issue by michaelwkudla** [nsmela/brachify#107]
All needles are supposed to be "interstitial" but there is some bug causing the first point in the needle (the interstitial point) to be dropped, thus creating an IC needle. Just on one needle. Very weird. It also doesn't have the pointy needle tip, so it seems like that part of the needle generation is being clipped somehow. See pic.

![image](https://github.com/nsmela/brachify/assets/25753746/c46f7f33-a233-4efb-aa9f-7495c4a1a4d4)

**Comment by nsmela** [comment]
I think the points are too close on that one.

**Comment by michaelwkudla** [comment]
resolved over at https://github.com/brachify/brachify/
