### ISSUE TITLE
Zero degree tip angle

### ISSUE THREAD

**Issue by michaelwkudla** [nsmela/brachify#85]
If the user puts in zero degrees, the channel doesn't go through the cylinder. 

- [ ] Let's make a hardcoded override that if the user inputs an angle less than 0.5 deg, that a straight tandem will be inserted instead (angle is zero).

**Comment by nsmela** [comment]
if the angle is less than ~35 deg, the tandem generated starts to get wonky. I was considering locking the angle spinbox to be between 35 and 60 degrees to solve this temporarily.

**Comment by michaelwkudla** [comment]
Moved to https://github.com/brachify/brachify/issues
